debug: true
server:
  port: 8080

auth0:
  # Replace with the API Identifier for your Auth0 API.
  audience: localhost:8080

# The following is standard Spring Security OAuth2 configuration.
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Replace with the domain of your Auth0 tenant.
          # Note the trailing slash is important!
          issuer-uri: https://kahvipaketti.eu.auth0.com/
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: salasana
    driver-class-name: org.postgresql.Driver